BaronaExercise/force-app/main/default/objects/Job_Applicant__c/Job_Applicant__c.object-meta.xml
<CustomObject>
    <label>Job Applicant</label>
    <nameField>
        <label>Job Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BaronaExercise/force-app/main/default/objects/Job_Applicant__c/fields/Job_Request__c.field-meta.xml
<CustomField>
    <fullName>Job_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Request</label>
    <referenceTo>Job_Request__c</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

BaronaExercise/force-app/main/default/objects/Job_Applicant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BaronaExercise/force-app/main/default/objects/Job_Request__c/Job_Request__c.object-meta.xml
<CustomObject>
    <label>Job Request</label>
    <nameField>
        <label>Job Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BaronaExercise/force-app/main/default/objects/Job_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BaronaExercise/force-app/main/default/classes/JobApplicantTriggerTest.cls
@isTest
public class JobApplicantTriggerTest {
@isTest
    public static void testUpdateTrigger(){
        String Status = 'Fulfilled';
        Job_Request__c jReq = [SELECT id,Status__c FROM Job_Request__c WHERE Status__c=:Status];
        Job_Applicant__c jAppl = [SELECT id,Job_Request__c FROM Job_Applicant__c WHERE Job_Request__c=:jReq.Id];
        jAppl.Status__c = 'Selected';
        update jAppl;
    }
    
}